name: navicat-keygen builds
on: workflow_dispatch

jobs:
  navicat-keygen-x86:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        shell: pwsh
        run: |
          pushd .
          cd ${env:VCPKG_INSTALLATION_ROOT}

          git reset --hard 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
          vcpkg install openssl:x86-windows-static

          git reset --hard f65d6947c7212618c00dcc99ecd53c47db97f8cd
          vcpkg install unicorn:x86-windows-static

          git pull
          vcpkg install fmt:x86-windows-static
          vcpkg install rapidjson:x86-windows-static
          vcpkg install keystone:x86-windows-static
          popd

      - name: Clone source
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: |
          vcpkg integrate install
          msbuild navicat-keygen.sln /p:Configuration=Release /p:Platform=x86
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keygen-x86.zip
          path: bin/x86-Release/*.exe

  navicat-keygen-x64:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          pushd .
          cd ${env:VCPKG_INSTALLATION_ROOT}

          git reset --hard 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
          vcpkg install openssl:x64-windows-static

          git reset --hard f65d6947c7212618c00dcc99ecd53c47db97f8cd
          vcpkg install unicorn:x64-windows-static

          git pull
          vcpkg install fmt:x64-windows-static
          vcpkg install rapidjson:x64-windows-static
          vcpkg install keystone:x64-windows-static
          popd

      - name: Clone source
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: |
          vcpkg integrate install
          msbuild navicat-keygen.sln /p:Configuration=Release /p:Platform=x64
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keygen-x64.zip
          path: bin/x64-Release/*.exe
